---
name: Terraform Destroy
on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: Expects the name of the repository to be confirmed
        required: true
        type: string

      aws-account-id:
        description: "The AWS account ID to deploy to"
        required: true
        type: string

      aws-role:
        description: "The AWS role to assume"
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  destroy:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-destroy.yml@main
    name: Terraform Destroy
    secrets:
      actions-id: "${{ secrets.ORG_ACTIONS_APP_ID }}"
      actions-secret: "${{ secrets.ORG_ACTIONS_APP_SECRET }}"
    with:
      aws-account-id: <ACCOUNT_ID>
      aws-role: <ROLE_NAME>
      enable-private-access: true
