---
name: Workflow Validation
on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/**"

permissions:
  contents: read

jobs:
  validate-workflows:
    uses: appvia/appvia-cicd-workflows/.github/workflows/github-workflow-validation.yml@9b6a5fd5f2fdcb76246ec73dbac6cb888f0fdf12 # main
    name: Validate GitHub Workflows
